name: Q1 Archive README

on:
  push:
    branches:
      - main

jobs:
  archive_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      - name: Push Q1_archive_README.md
        run: |
          git config --global user.name "OcsCgn"
          git config --global user.email "Oscar.cocagne@free.fr"
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md"
          git push
