name: Q3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # JY: 
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
    - name: Copier README.md dans Q3_archive_java.txt
      run: 
          cp Q3.java Q3_archive_java.txt
      
    - name: JY commit et push
      run: |
        git config --global user.name OcsCgn
        git config --global user.email Oscar.cocagne@free.fr
        git add -A
        git status
        git commit -m "exécution de maven"
        git push
