name: Q3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # JY: 
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
    - name: Copier README.md dans Q3_archive_java.txt
      run: 
          cp Q3.java Q3_archive_java.txt


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      
    - name: JY commit et push
      run: |
        git config --global user.name OcsCgn
        git config --global user.email Oscar.cocagne@free.fr
        git add -A
        git status
        git commit -m "exécution de maven"
        git push
